version: '3.8'

services:
  # Gateway Service
  gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"  # Expose the gateway on port 3000
    depends_on:
      - attendance-service
      - employee-service
      - payroll-service
      - mongo  # Ensures the gateway starts after other services
    networks:
      - microservice-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb

  # Attendance Service
  attendance-service:
    build:
      context: ./attendance-service/
      dockerfile: Dockerfile.attendance
    environment:
      - MURL=mongodb://mongo:27017/attendanceDB  # Using a dedicated DB
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm
      - RMQ_URL=amqps://uszqamll:ZS583QWOVfj1fe9TaJFdd79WoRCoVCmA@fuji.lmq.cloudamqp.com/uszqamll
    depends_on:
      - mongo
    networks:
      - microservice-network

  # Employee Service
  employee-service:
    build:
      context: ./employee-service/
      dockerfile: Dockerfile.employee
    environment:
      - MURL=mongodb://mongo:27017/employeeDB  # Using a dedicated DB
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm
      - RMQ_URL=amqps://uszqamll:ZS583QWOVfj1fe9TaJFdd79WoRCoVCmA@fuji.lmq.cloudamqp.com/uszqamll
    depends_on:
      - mongo
    networks:
      - microservice-network

  # Payroll Service
  payroll-service:
    build:
      context: ./payroll-service/
      dockerfile: Dockerfile.payroll
    environment:
      - MURL=mongodb://mongo:27017/payrollDB
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm
    depends_on:
      - mongo
    networks:
      - microservice-network

  # MongoDB Service
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data to a volume
    ports:
      - "27017:27017"  # Expose MongoDB on the default port for internal and external access
    networks:
      - microservice-network


volumes:
  mongodb_data:  # This will persist MongoDB data

networks:
  microservice-network:
    driver: bridge  # This specifies the default network driver for inter-container communication
