# Use official Node.js image from Docker Hub
FROM node:23

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy the gateway package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies for the gateway
RUN npm install

# Copy the gateway code
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Start the gateway (app)
CMD ["npm", "start"]
